// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetTest():Promise<Array<main.Test>>;

export function Greet(arg1:string):Promise<string>;

export function Struct():Promise<main.Embedding>;

export function Test():Promise<string>;
