// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTest() {
  return window['go']['main']['App']['GetTest']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Struct() {
  return window['go']['main']['App']['Struct']();
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
